services:

  amazeeio-dnsmasq:
    Config:
      Labels:
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct

  amazeeio-haproxy:
    Config:
      Labels:
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct

  amazeeio-mailhog:
    Config:
      Labels:
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct

  amazeeio-ssh-agent:
    Config:
      Labels:
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct

  amazeeio-ssh-agent-add-key:
    Config:
      Labels:
        - pygmy.enable: false

  amazeeio-ssh-agent-show-keys:
    Config:
      Labels:
        - pygmy.enable: false

  amazeeio-portainer:
    Config:
      Image: portainer/portainer
      Env:
        - "AMAZEEIO=AMAZEEIO"
        - "AMAZEEIO_URL=portainer.docker.amazee.io"
        - "AMAZEEIO_HTTP_PORT=9000"
      Labels:
        - pygmy.enable: true
        - pygmy.name: amazeeio-portainer
        - pygmy.network: amazeeio-network
        - pygmy.weight: 23
        - pygmy.url: http://portainer.docker.amazee.io
        - pygmy.hocuspocus: 42
        - pygmy.abracadabra: true
        - pygmy.opensesame: correct
      ExposedPorts:
        9000/tcp: {}
    HostConfig:
      Binds:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      PortBindings:
        8000/tcp:
          - HostPort: 8200
        9000/tcp:
          - HostPort: 8100

  pygmy-cowsay:
    Config:
      Image: mbentley/cowsay
      Cmd:
        - holy
        - ship
      Labels:
        - pygmy.enable: true
        - pygmy.discrete: false
        - pygmy.name: pygmy-cowsay
        - pygmy.output: true
        - pygmy.weight: 99
    HostConfig:
      AutoRemove: true

volumes:
  portainer_data:
    Name: portainer_data